---
title: "Input specification creation and management for the data from the Dry Forest plots from Colombia (red BST-COL)."
author: "Marius Bottin"
date: '`r format(Sys.time(), "%d %B, %Y")`'
output: 
   pdf_document:
     toc: true
     toc_depth: 5
     number_sections: true
     latex_engine: xelatex
always_allow_html: true
fontsize: 11pt
geometry: "left=3cm,right=3cm,top=3cm,bottom=3cm"
linkcolor: gray
urlcolor: blue
citecolor: cyan
header-includes:
  - \usepackage{colortbl}
  - \usepackage{xcolor}       
  - \usepackage{lscape}
  - \usepackage{fvextra}
  - \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
--- 


***************

```{r, setup, message=F, warning=F, include=F}
require(knitr)&require(RPostgreSQL)&require(formatR)&require(kableExtra)
def.chunk.hook  <- knitr::knit_hooks$get("chunk")
knitr::knit_hooks$set(chunk = function(x, options) {
  x <- def.chunk.hook(x, options)
  ifelse(options$size != "normalsize", paste0("\n \\", options$size,"\n\n", x, "\n\n \\normalsize"), x)
})
opts_chunk$set(cache=F,fig.path="../../Fig/input_spec_BST",tidy='styler',cache.rebuild = F,formatSQL = TRUE, size='scriptsize',
               echo=T, message=T, warning=T)
options(knitr.kable.NA = '---')
```

# Leer los archivos de specification


```{r}
folSpec <- "../inputSpec/permanentBstCsv/"
A <- lapply(paste0(folSpec,dir(folSpec, pattern = "\\.csv$")),read.csv)
A[[1]]$typeof[A[[1]]$typeof=="character"&!is.na(A[[1]]$maxChar)]<- "varchar"
A[[1]]$typeof[A[[1]]$typeof=="character"&is.na(A[[1]]$maxChar)]<- "text"
A[[1]]$typeof[A[[1]]$typeof=="double"]<- "double precision"
```

# Insert tables

```{r}
require(RPostgreSQL)
sib_adm <- dbConnect(PostgreSQL(), dbname = "sib_plot", user = "sib_adm", password = "sib")
dbBegin(sib_adm)
dbWriteTable(conn = sib_adm,name = c("spec","tmp_table"),value = A[[2]], temporary = T)
#dbReadTable(sib_adm,c("spec","tmp_table"))
tabs <- dbSendQuery(sib_adm,
"INSERT INTO spec.in_tables(tablename,mandatory,regex_reco)
SELECT tablename, mandatory, regex_reco
FROM spec.tmp_table
"
)
nb_tabs <- dbGetRowsAffected(tabs)
maxIdTab <- dbGetQuery(sib_adm,"SELECT max(id_tab) nb FROM spec.in_tables")$nb
lineMinTab <- maxIdTab - nb_tabs
dbClearResult(tabs)
dbWriteTable(sib_adm, name = c("spec", "tmp_fields"), value = A[[1]][,!apply(A[[1]],2,function(x)all(is.na(x)))], temporary = T)
que <- "
WITH with_tabcd AS (
SELECT t.id_tab,f.*
FROM spec.tmp_fields f
LEFT JOIN spec.in_tables t ON f.table = t.tablename AND t.id_tab > $1
)
INSERT INTO spec.in_fields(cd_tab,fieldname,example,regex_reco,typeof,max_char,mandatory,extra,regex_field,comment)
(SELECT id_tab, field, example, \"recoField\", typeof,\"maxChar\",mandatory,false,regex,NULL
FROM with_tabcd)
"
fie <- dbSendQuery(sib_adm, que, params = list(lineMinTab))
nbFie <- dbGetRowsAffected(fie)
ins_for <- dbSendQuery(sib_adm,"INSERT INTO spec.in_format(formatname,version,created_by,creation_date,install_date,description)
            VALUES('BST_csv','0.1','marius',NOW(),NOW(),'Format for the \"red BST-COL\" consisting of a group of csv files')
            ")
dbClearResult(ins_for)
dbClearResult(fie)
ins_rel_tab <- dbSendQuery(sib_adm,
           "INSERT INTO spec.in_rel_tab
            SELECT fo.id_for,ta.id_tab
            FROM 
              spec.in_format fo,
              spec.in_tables ta
            WHERE fo.id_for= (SELECT max(id_for) FROM spec.in_format)
              AND
                ta.id_tab>$1
            ",params = list(lineMinTab))
dbClearResult(ins_rel_tab)
ins_rel_fie <- dbSendQuery(sib_adm,"INSERT INTO spec.in_rel_field
            SELECT fo.id_for,fi.id_field
            FROM
              spec.in_format fo,
              spec.in_fields fi
            WHERE fo.id_for= (SELECT max(id_for) FROM spec.in_format)
              AND
                fi.id_field>$1
            ",params=list(dbGetQuery(sib_adm,"SELECT max(id_field) nb FROM spec.in_fields")$nb - nbFie))
dbClearResult(ins_rel_fie)
dbRemoveTable(sib_adm,c("spec","tmp_table"))
dbRemoveTable(sib_adm,c("spec","tmp_fields"))
dbCommit(sib_adm)
```




```{r}
dbDisconnect(sib_adm)
```

